### ISSUE TITLE
Can't install workload to Scale unit @A

### ISSUE THREAD

**Issue by ABOZH** [microsoft/SCMScaleUnitDevTools#76]
When trying instal workload to Scale Unit @A I receive error
Installing the SYS workload
```log
Install workload on scale unit failed.

System.Exception: [500]: Error - {
  "Message": "An exception occured when invoking the operation - @ScaleUnitManagement:FailedInitializeScaleUnit Response from hub is not valid. IsSuccessStatusCode is false. Response from hub =>\n{\r\n  \"Message\": \"An exception occured when authorizing - Entry point security access denied to current user for operation 'getInitializationData' on service 'ScaleUnitInitializationService'.\",\r\n  \"ExceptionType\": \"XppServicesAuthorizationException\",\r\n  \"ActivityId\": \"03774dd1-9b76-0001-e7b3-7703769bd701\"\r\n}",
  "ExceptionType": "ErrorException",
  "ActivityId": "022bbb8e-9c05-0001-3ece-2b02059cd701"
}
   at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.AOSClient.SendRequest(String path, String payload) in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs:line 178
   at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.AOSClient.WriteWorkloadInstances(List`1 workloadInstances) in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs:line 81
   at ScaleUnitManagement.WorkloadSetupOrchestrator.ScaleUnitWorkloadInstaller.<InstallWorkloadsOnScaleUnit>b__4_0() in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs:line 92
   at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.ReliableRun.Execute(Func`1 command, String commandName) in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/ReliableRun.cs:line 23
```

**Comment by Omaaarz** [comment]
@ABOZH  Could you explain more what the steps you have taken on both hub and spoke? which version of AX you are on as well?

**Comment by AndreasHassing** [comment]
@ABOZH can you check which user is assigned to your Azure App for Scale Unit Management on the Scale Unit (from SysAADClientTable menu item: "Azure Active Directory Applications" if I remember correctly)?

Looking at the error details, it looks like a user other than "ScaleUnitManagement" or "Admin" is assigned to your AAD app specified [here](https://github.com/microsoft/SCMScaleUnitDevTools/blob/c1bc4ca1a4e6df1efb81e6cfb3e1716df890844e/src/ScaleUnitManagement/UserConfig.sample.xml#L63-L67).

**Comment by ABOZH** [comment]
> Could you explain more what the steps you have taken on both hub and spoke? which version of AX you are on as well?

@Omaaarz 
I'm on 10.0.20 on both environments, both environments are lcs hosted tier 1 dev-box.
I walked strictly according to the instructions https://github.com/microsoft/SCMScaleUnitDevTools/wiki/Step-by-step-usage-guide
1. Prepared a config file and used it on both environments
2. Run the utility and initialized the hub first, then the scale unit (Initialize the hybrid topology)
3. Completed preparation on the hub and scale unit (Prepare environments for workload installation)
4. I installed the workload on the hub, but when I tried to install it on the scale unit I got an error

**Comment by AndreasHassing** [comment]
Hi @ABOZH, thanks for providing those details.

Can you let us know: do you have 2 AAD apps for inter-AOS communication and management?

And if possible, can you upload your `UserConfig.xml` _WITHOUT THE SECRETS!_ so we can investigate further? 😊

**Comment by ABOZH** [comment]
> Hi @ABOZH, thanks for providing those details.
> 
> Can you let us know: do you have 2 AAD apps for inter-AOS communication and management?
> 
> And if possible, can you upload your `UserConfig.xml` _WITHOUT THE SECRETS!_ so we can investigate further? 😊

Hi @AndreasHassing 
I use 1 AAD apps
please look at my config in attach
thank
[UserConfig.zip](https://github.com/microsoft/SCMScaleUnitDevTools/files/7083976/UserConfig.zip)

**Comment by AndreasHassing** [comment]
Ah, that is most likely it then. You need 2 apps; one for the tool to talk to the environments and another for inter-AOS communication. They have different privilege models and will step on each-other's toes if you use the same AAD app for both.

From [our documentation in the Wiki](https://github.com/microsoft/SCMScaleUnitDevTools/wiki/Step-by-step-usage-guide#aad-application-registrations) (excerpt):
> Create at least two Applications in Azure Active Directory.
>
> The first will provide the authorization for the data flow between hub and the scale unit (InterAOSAADConfiguration). The other ones will control the access of the configuration tool to the development environments. You can use the same one here for multiple scale unit instances.

You will need to perform some cleanup in your Hub and Spoke and afterwards re-run steps 1 and 2 (Initialize and Prepare, respectively):
```sql
DELETE FROM SysAADClientTable WHERE aadClientId = '<the app ID you currently have in UserConfig.xml>';
```

**Comment by ABOZH** [comment]
@AndreasHassing  thanks, all worked well 
did not initially interpret this proposal correctly "You can use the same one here for multiple scale unit instances"
Thank you for support

**Comment by AndreasHassing** [comment]
Thanks for coming back to us on this @ABOZH, I created #79 to avoid others falling into this pit going forward 😊.

**Comment by ABOZH** [comment]
there was a need to restore a clean empty database to the scale unit environment, and now the error repeats, I can not install the workload on the scale unit
![image](https://user-images.githubusercontent.com/89694939/133451454-67ec77e0-946b-4d8d-b55d-c31b3fbb1ad4.png)
 at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.AOSClient.SendRequest(String path, String payload) in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs:line 178
   at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.AOSClient.GetWorkloadInstances() in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs:line 128
   at ScaleUnitManagement.WorkloadSetupOrchestrator.WorkloadDeleter.<DeleteWorkloadsFromScaleUnit>b__1_0() in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadDeleter.cs:line 19
   at ScaleUnitManagement.WorkloadSetupOrchestrator.Utilities.ReliableRun.Execute(Func`1 command, String commandName) in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/ReliableRun.cs:line 23

[9/15/2021 2:41:33 PM] Error during Delete workloads from scale unit @A:
System.Exception: [401]: Error - {
  "Message": "An exception occured when authorizing - Entry point security access denied to current user for operation 'get' on service 'SysWorkloadInstanceService'.",
  "ExceptionType": "XppServicesAuthorizationException",
  "ActivityId": "ba76522e-aa00-0003-2d11-77ba00aad701"

**Comment by AndreasHassing** [comment]
Hey @ABOZH, this seems unrelated to what this issue was first about. Can you create a new issue so we have tracking and discoverability without getting deep issue threads 😊.

**Comment by ABOZH** [comment]
ok thank @AndreasHassing 
I'm open another issue.
